# freebsd/{distro_pkgs.ini,distro_pkgmgr_funcs.sh}
# to use variables|functions, source these file(s):
# source distro_pkgs.ini ; source distro_pkgmgr_funcs.sh
# ${pkgmgr_install} ${pkgs_cmdln_tools} 2> /tmp/pkgsInstall_stderr.txt | tee /tmp/pkgsInstall_stdout.txt

pkgs_cmdln_extras="todo ledger msmtp isync mutt s-nail transmission-cli rtorrent irssi finch rclone cmus"
# fdm
## pip install --user xx: khal khard vdirsyncer offlineimap topydo beancount getmail6

pkgs_emulation_utils="edk2-qemu-x64 qemu dnsmasq sshpass cmake"
# py311-pip py311-timelib packer bhyve-firmware grub2-bhyve ezjail vm-bhyve
## pip install [--break-system-packages] --user xx: ansible-core salt

pkgs_filesys_utils="fusefs-exfat exfat-utils"
# exfat note (need add to /etc/rc.shutdown): sync ; umount /mnt/DataX

# anacron rpcbind nfsserver nfs_server
services_enabled="ntpd dbus pf pflog avahi-daemon nfsclient nfs_client cupsd"
services_disabled="clamav_freshclam clamav_clamd lpd"
pkgs_cmdln_tools="dbus anacron clamav sudo python en-freebsd-doc mc rlwrap nano aria2 netcat bzip2 gtar zip unzip 7-zip gnupg password-store keychain base64 openssl gnutls ca_root_nss nss_mdns w3m qpdf sqlite3 git mercurial tcpdump nmap pinentry-curses cdialog screen tmux cups-pdf rsync"
# clamav py311-pip


xorg_pkg="xorg-server"
pkgs_xorg_addons="xorg-minimal xf86-video-scfb xf86-video-intel xf86-input-libinput xf86-input-evdev xterm xscreensaver"

# ? hald
uiservices_enabled_kde="dbus moused seatd sddm"
uiservices_disabled_kde=""
# [seatd | polkit]
pkgs_deskenv_kde="dbus seatd xorg-minimal xf86-video-scfb xdg-utils xdg-user-dirs drm-kmod utouch-kmod kf6-breeze-icons sddm plasma6-plasma konsole dolphin"
# kate conky

# ? hald
uiservices_enabled_xfce="dbus moused seatd gdm"
uiservices_disabled_xfce=""
# [seatd | polkit]
pkgs_deskenv_xfce="dbus seatd xorg-minimal xf86-video-scfb xdg-utils xdg-user-dirs drm-kmod utouch-kmod gdm xfce"
# gvfs wpa_supplicant_gui conky

# ? hald
uiservices_enabled_lxqt="dbus moused seatd sddm"
uiservices_disabled_lxqt=""
# [seatd | polkit]
pkgs_deskenv_lxqt="dbus seatd xorg-minimal xf86-video-scfb xdg-utils xdg-user-dirs drm-kmod utouch-kmod kf6-breeze-icons sddm gvfs lxqt"
# menumaker wpa_supplicant_gui conky


# possibly extra Qt:Gtk deskenv apps
# ----------------------------------------
# (disk utils) partitionmanager:gparted
# (ifc connect) cmst:wicd bluez-qt:blueman
# (editors, office apps) :geany libreoffice :gnucash
# (file share) transmission-qt:transmission-gtk luckybackup:grsync
# (archivers) ark:xarchiver
# (clipboard tool) qlipper:parcellite
# (crypt utils) keepassxc:keepass2 qtpass: kwalletmanager:seahorse
# (browser) :chromium falkon:firefox-esr
# (email) :thunderbird
# (print utils) skanlite:simple-scan qpdfview:epdfview
# (db utils) sqlitebrowser:
# (IM-IRC) quassel:hexchat :pidgin
# (vcs gui) qgit:gitg tortoisehg:
# (traffic util) nmapsi4:zenmap wireshark
# (media plyr) clementine:gmusicbrowser smplayer:totem
# (audio tool) pavucontrol-qt:pavucontrol k3b:brasero
# (image tool) lximage-qt:gpicview :gimp
# (webcam tool) kamoso:guvcview
# (PIM tools) :gsimplecal :orage
# (ebook utils) calibre: okular:fbreader


# addons browser: AdBlock Plus, HTTPS Everywhere, uBlock Origin, NoScript,
#   User-Agent Switcher

# addons thunderbird 78+: Manually sort folders, Remove Duplicate Messages,
#   Provider f/CalDAV & CardDAV, TbSync, ? ImportExportTools NG, ? TorBirdy


labservices_enabled="dbus"
labservices_disabled=""
#(userifc)# use OS package manager to install: py311-tkinter py311-pygobject
#  py311-gobject3 py311-qt5 py311-pyside2 py311-qt5-pyqt pyotherside-qt5 py311-wxPython42
#(crypto)# use OS package manager to install: py311-gpg
pkgs_lang_py="dbus xauth ca_root_nss"
# py311-pip py311-setuptools pychecker jython

lang_c_userifc="ncurses tcl86 tk86 gtk3"
# "qt5-widgets wx32-gtk3"
lang_c_crypto="libgcrypt openssl gnutls mbedtls3 gpgme"
# ""
lang_c_dbase="libdbi sqlite3 sqlitejdbc postgresql16-server mysql84-server mariadb114-server hiredis mongo-c-driver"
# ""
lang_c_network="curl"
# ""
pkgs_lang_c="dbus xauth ca_root_nss cmake autotools gmake gdb pkgconf splint check cunit log4c pcre json-glib yajl libyaml lcov swig"
# gcc ddd valgrind doxygen rubygem-rake premake4 cppcheck bcunit
## pip install --user xx: meson ninja scons

#(dbase)# use OS package manager to install: sqlitejdbc postgresql-jdbc
#  mariadb-java-client mysql-connector-java [mongo|jedis|redisson]-java-driver
pkgs_lang_java="dbus xauth ca_root_nss openjdk11 openjdk"
# apache-ant maven gradle sbt
#default_path_to_fx="[/usr/local|/opt]/openjfx[14]/lib"
# dnld: https://download2.gluonhq.com/openjfx/[11]/openjfx-[11]_[linux]-[x64]_bin-[sdk|jmods].zip

#(userifc)# use OS package manager to install: gtk-sharp30
pkgs_lang_cs="dbus xauth ca_root_nss dotnet mono msbuild fsharp"
# osslsigncode
## NOTE: missing *.dll(s) errors - edit [/usr/local]/etc/mono/config
##  example: libgobject-2.0 -> libgobject-2.0-0.dll
# dnld: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
# linux-dotnet-sdk gtk-sharp30

pkgs_lang_fs="dbus xauth ca_root_nss dotnet mono msbuild fsharp"
# osslsigncode


pkgs_lang_rb="ruby"
# jruby

pkgs_lang_go="go gpm"

pkgs_lang_rs="rust"

pkgs_lang_scala="dbus xauth ca_root_nss openjdk11 openjdk"
# apache-ant
pkgs_lang_clj=""
# clojure leiningen

pkgs_lang_hs="ghc hs-stack"

pkgs_lang_ml="ocaml ocaml-opam ocaml-dune"

pkgs_lang_scm="gauche slib guile2 sagittarius-scheme"

pkgs_lang_lisp="sbcl clisp"

#pkgs_lang_swift="libedit icu ncurses"
## ?? Incompatible w/ FreeBSD ?? dnld: https://download.swift.org/swift-[5.6]-release/[amazonlinux2][-aarch64]/swift-[5.6]-RELEASE/swift-[5.6]-RELEASE-[amazonlinux2][-aarch64].tar.gz[.sig]
