---

# for runit service ops w/ Ansible,Saltstack
- file: src={{item.srcX}} dest={{item.destX}} state=link
  ignore_errors: true
  loop: [{srcX: '/etc/runit/sv', destX: '/etc/sv'}
        #, {srcX: '/etc/runit/runsvdir/default', destX: '/var/service'}
        , {srcX: '/run/runit/service', destX: '/var/service'}
        ]
  when: service_mgr == 'runit'
