---

- lineinfile:
    path: /etc/rc.local
    state: present
    mode: 'ugo+x'
    regexp: '.*dbus-uuidgen.*'
    #line: '/usr/bin/dbus-uuidgen --ensure=/etc/machine-id'
    line: '/usr/bin/dbus-uuidgen --ensure'
  ignore_errors: true
