---

- block:
  - name: "Fix .NET access problem SSL CA cert path"
    file:
      path: /compat/linux/etc/pki/tls/certs
      state: directory

  - file:
      src: /usr/local/share/certs/ca-root-nss.crt
      dest: /compat/linux/etc/pki/tls/certs/ca-bundle.crt
      state: link
    ignore_errors: true
