---

- block:
  - block:
    - service: name=pamac state=stopped
      ignore_errors: true

    - file: path=/var/lib/pacman/db.lck state=absent
      ignore_errors: true
    when: pkg_mgr == 'pacman'

  - block:
    - shell: |
        apt-config dump | grep -we Recommends -e Suggests | sed 's|1|0|' | \
          tee /etc/apt/apt.conf.d/999norecommends
      ignore_errors: true

    - lineinfile:
        path: /etc/apt/apt.conf.d/99force-ipv4
        state: present
        create: true
        regexp: 'Acquire::ForceIPv4.*;'
        line: '#Acquire::ForceIPv4 "true";'
      ignore_errors: true

    - lineinfile:
        path: /etc/apt/apt.conf.d/99retries03
        state: present
        create: true
        regexp: '^Acquire::Retries.*;'
        line: 'Acquire::Retries "3";'
      ignore_errors: true
    when: pkg_mgr in ['apt', 'apt_rpm']

  - block:
    - lineinfile:
        path: /etc/zypp/zypp.conf
        state: present
        create: true
        regexp: '.*solver.onlyRequires.*=.*'
        line: 'solver.onlyRequires = true'
      ignore_errors: true

    - lineinfile:
        path: /etc/zypp/zypp.conf
        state: present
        create: true
        regexp: '.*installRecommends.*=.*'
        line: 'installRecommends = no'
      ignore_errors: true

    - package: use='{{pkg_mgr}}' name=netcat-openbsd state=absent
      ignore_errors: true
    when: pkg_mgr == 'zypper'

  - shell: |
      dnf --setopt=install_weak_deps=False config-manager --save
      dnf config-manager --dump | grep -we install_weak_deps
    ignore_errors: true
    when: pkg_mgr == 'dnf'

  - block:
    - name: "Refresh pkg db (pkg_mgr: {{pkg_mgr}})"
      package: use='{{pkg_mgr}}' name=pkg
      register: out
      when: pkg_mgr == 'pkgng'

    - name: "Refresh pkg db (pkg_mgr: {{pkg_mgr}})"
      package: use='{{pkg_mgr}}' update_cache=true
      register: out
      when: pkg_mgr not in ['pkgng', 'openbsd_pkg']
    - debug: var=out

    - name: "Display cmdline-tools packages"
      #shell: . /root/scripts/distro_pkgs.ini ; echo ${pkgs_cmdln_tools}
      #ignore_errors: true
      debug: var=distro_pkgs.pkgs_cmdln_tools

- block:
  - block:
    - name: "Enter 'yes' to continue [noYES]:"
      pause:
        prompt: "Enter 'yes' to continue, else stop playbook [noYES]: "
      register: response

    - name: "Check autoconfirm or response is 'yes'"
      #fail: msg="Stopping playbook"
      meta: end_host
      when: not (('' == response.get('user_input', '') or response.user_input | default(true))|bool)
    when: not (autoconfirm | default(true))|bool

  - package: use='{{pkg_mgr}}' name='{{pkgs_cmdlntools_commasep}}' state=present extra_args_precommand='--ignore-unknown'
    ignore_errors: true
    when: pkg_mgr == 'zypper'

  - package: use='{{pkg_mgr}}' name='{{pkgs_cmdlntools_commasep}}' state=present skip_broken=true
    ignore_errors: true
    when: pkg_mgr == 'dnf'

  - block:
    - package: use='{{pkg_mgr}}' name='{{pkgs_cmdlntools_commasep}}' state=present
      ignore_errors: true
      register: out

    - name: retry failed install
      package: use='{{pkg_mgr}}' name='{{item}}' state=present
      ignore_errors: true
      loop: '{{pkgs_cmdlntools_list}}'
      when: out.get('failed', false)
    when: pkg_mgr not in ['zypper', 'dnf']
  vars:
    pkgs_cmdlntools_commasep: '{{distro_pkgs.pkgs_cmdln_tools.replace(" ", ",")}}'
    pkgs_cmdlntools_list: '{{distro_pkgs.pkgs_cmdln_tools.split(" ")}}'


- shell: '{{idsuffix_cmd}}'
  ignore_errors: true
  register: idsuffix_result

- block:
  - name: "Fix hostname regexp box.0000"
    replace:
      path: "{{item}}"
      regexp: '{{hostname_0000_if}}0000'
      replace: '{{hostname_0000_if}}{{idsuffix_result.stdout}}'
    ignore_errors: true
    loop: '{{hostname_chgfiles}}'

  - hostname: name={{hostname_0000_if}}{{idsuffix_result.stdout}}
    ignore_errors: true
  when: ansible_facts.get("nodename") is match(".*box.0000")
  vars:
    hostname_0000_if: '{{ansible_facts.get("nodename")|regex_search("(.*box.)")}}'

- shell: java -version
  register: out_java
  ignore_errors: true

#- find:
#    #paths: /bin, /usr/bin, /usr/local/bin, /usr/pkg/bin
#    paths: /
#    recurse: true
#    patterns: 'java'
#  register: found_result

- block:
  - shell: |
      #dirname $(dirname $(realpath $(which java)))
      realpath $(which java) | sed "s:/bin/java::"
    register: out_javahome

  #- lineinfile:
  #    path: /etc/csh.cshrc
  #    state: present
  #    regexp: '^setenv JAVA_HOME.*'
  #    line: 'setenv JAVA_HOME {{out_javahome}}'
  #  ignore_errors: true
  #  when: ansible_facts.get("env")["SHELL"] is search("csh")

  #- lineinfile:
  #    path: /etc/bash.bashrc
  #    state: present
  #    regexp: '^export JAVA_HOME.*'
  #    line: 'export JAVA_HOME={{out_javahome}}'
  #  ignore_errors: true
  #  when: ansible_facts.get("env")["SHELL"] is search("bash")

  #- lineinfile:
  #    path: /etc/ksh.kshrc
  #    state: present
  #    regexp: '^export JAVA_HOME.*'
  #    line: 'export JAVA_HOME={{out_javahome}}'
  #  ignore_errors: true
  #  when: ansible_facts.get("env")["SHELL"] is search("ksh")

  - lineinfile:
      path: /etc/profile.d/jdk.sh
      state: present
      create: true
      regexp: '^export JAVA_HOME.*'
      line: 'export JAVA_HOME={{out_javahome}}'
    ignore_errors: true

  - lineinfile:
      path: /etc/fstab
      state: present
      regexp: '^fdesc'
      line: 'fdesc  /dev/fd  fdescfs  rw  0  0'
    ignore_errors: true
    when: ansible_facts.get('system')|lower != 'linux'
  when: not out_java.get('failed', false)
  #when: 0 != found_result.matched

- block:
  ##                                 mode=['g+ws,+t' | 3775]
  #- file: follow=true path=/var/mail group=wheel mode='g+ws,+t'
  #  ignore_errors: true
  #  when: variant in ['netbsd', 'openbsd']

  #                                 mode=['g+ws,+t' | 3775]
  - file: follow=true path=/var/mail group=postfix mode='g+ws,+t'
    ignore_errors: true
    when: variant in ['mageia', 'pclinuxos']

  #                                 mode=['g+ws,+t' | 3775]
  - file: follow=true path=/var/mail group=mail mode='g+ws,+t'
    ignore_errors: true
    #when: variant not in ['mageia', 'netbsd', 'openbsd', 'pclinuxos']
    when: variant not in ['mageia', 'pclinuxos']

- block:
  - name: "Setup skeleton paths"
    file:
      path: '{{item}}'
      state: directory
    loop: '{{skel_dirs}}'

  - shell: "cp -a /root/init/common/skel/{{item.srcskel}} {{skeldir_par}}/{{item.destskel}}"
    ignore_errors: true
    loop: '{{skelmaps_srcdest}}'


- include_tasks: '{{cfgfile}}'
  with_first_found:
    - files:
      - 'cmdlntools/config_{{variant}}.yml'
      skip: True
  loop_control: {"loop_var": "cfgfile"}

- include_tasks: '{{cfgfile}}'
  loop: [common/config_cron.yml, common/config_smtp.yml
        , common/config_firewall.yml, common/misc_config.yml]
  loop_control: {"loop_var": "cfgfile"}

- shell: |
    lpstat -t
  ignore_errors: true

- block:
  - name: "Enable service(s) ({{service_mgr}})"
    systemd_service: name={{item}} enabled=true masked=false
    ignore_errors: true
    loop: '{{distro_pkgs.services_enabled.split(" ")}}'
    when: service_mgr == 'systemd'

  - name: "Disable service(s) ({{service_mgr}})"
    systemd_service: name={{item}} enabled=false masked=true
    ignore_errors: true
    loop: '{{distro_pkgs.services_disabled.split(" ")}}'
    when: service_mgr == 'systemd'

  - name: "Enable service(s) ({{service_mgr}})"
    service: name={{item}} enabled=true
    ignore_errors: true
    loop: '{{(distro_pkgs.services_enabled|replace("rsyslog ", "")).split(" ")}}'
    when: service_mgr == 'openrc'

  - name: "Enable service rsyslog runlevel boot ({{service_mgr}})"
    service: name=rsyslog enabled=true runlevel=boot
    ignore_errors: true
    when: service_mgr == 'openrc'

  - name: "Disable service(s) ({{service_mgr}})"
    service: name={{item}} enabled=false
    ignore_errors: true
    loop: '{{(distro_pkgs.services_disabled|replace("syslog ", "")).split(" ")}}'
    when: service_mgr == 'openrc'

  - name: "Disable service syslog runlevel boot ({{service_mgr}})"
    service: name=syslog enabled=false runlevel=boot
    ignore_errors: true
    when: service_mgr == 'openrc'

  - name: "Enable service(s) ({{service_mgr}})"
    service: name={{item}} enabled=true
    ignore_errors: true
    loop: '{{distro_pkgs.services_enabled.split(" ")}}'
    when: service_mgr not in ['systemd', 'openrc']

  - name: "Disable service(s) ({{service_mgr}})"
    service: name={{item}} enabled=false
    ignore_errors: true
    loop: '{{distro_pkgs.services_disabled.split(" ")}}'
    when: service_mgr not in ['systemd', 'openrc']

- block:
  - name: "Send email sample using sendmail"
    shell: |
      cat << EOF | sendmail -t root
      To: packer
      Subject: Subject sample

      Email sample
      EOF
    ignore_errors: true
    register: out

  - name: "Send sample email using mail"
    shell: |
      echo Sample email | mail -u vagrant -s "Sample subject" root packer
    ignore_errors: true
    register: out
    when: ansible_facts.get('system')|lower in ['freebsd']

  - block:
    #- name: "Send sample email using mail"
    #  shell: |
    #    echo Sample email | mail -r vagrant@{{ansible_facts.get("nodename")}} \
    #      -s "Sample subject" root packer
    #  ignore_errors: true
    #  register: out
    #  when: variant in ['alpine', 'debian']

    - find:
        paths: /bin,/usr/bin,/usr/local/bin,/usr/pkg/bin
        recurse: true
        patterns: 'nail,s-nail,mailx'
      ignore_errors: true
      register: found_mailcmds

    - shell: |
        #find /bin /usr/bin /usr/local/bin /usr/pkg/bin -name "nail" \
        #  -o -name "s-nail" -o -name "mailx" | head -n1
        which nail s-nail mailx | head -n1
      ignore_errors: true
      register: out_mailcmd

    - name: "Send sample email using {{mail_cmd}}"
      shell: |
        echo Sample email | {{mail_cmd}} -r vagrant@{{ansible_facts.get("nodename")}} \
          -s "Sample subject" root packer
      ignore_errors: true
      register: out
      #when: variant not in ['alpine', 'debian'] and 0 != found_mailcmds.matched
      vars:
        #mail_cmd: '{{(found_mailcmds.files[0].path | default("mail"))|basename}}'
        mail_cmd: '{{(out_mailcmd.stdout_lines[0] | default("mail"))|basename}}'
    when: ansible_facts.get('system')|lower not in ['freebsd']

- block:
  - name: "Clean pkg cache (pkg_mgr: {{pkg_mgr}})"
    package: use='{{pkg_mgr}}' clean=true
    register: out
    when: pkg_mgr in ['apt', 'pkgin', 'apt_rpm']

  - name: "Clean pkg cache (pkg_mgr: {{pkg_mgr}})"
    shell: '{{pkgclean_cmd}}'
    ignore_errors: true
    register: out
    when: pkg_mgr not in ['apt', 'pkgin', 'apt_rpm']
  - debug: var=out.stdout_lines

