---

- shell: |
    sed -i 's|.*solver.onlyRequires.*=.*|solver.onlyRequires = true|' \
      /etc/zypp/zypp.conf
    sed -i 's|.*installRecommends.*=.*|installRecommends = no|' \
      /etc/zypp/zypper.conf
  ignore_errors: true

- package:
    use: '{{ansible_facts.get("pkg_mgr") or pkg_mgr}}'
    name: netcat-openbsd
    state: absent

- package:
    use: '{{ansible_facts.get("pkg_mgr") or pkg_mgr}}'
    name: [enhanced_base, apparmor, sw_management]
    type: pattern
    state: present

- lineinfile:
    path: /etc/bash.bashrc
    state: present
    regexp: '^export JAVA_HOME.*'
    line: 'export JAVA_HOME={{distro_pkgs.default_java_home}}'
  ignore_errors: true

- file:
    path: '{{distro_pkgs.default_java_home}}'
    state: directory

- lineinfile:
    path: '{{distro_pkgs.default_java_home}}/release'
    state: present
    regexp: '^JAVA_VERSION.*'
    line: 'JAVA_VERSION={{distro_pkgs.default_java_version}}'
  ignore_errors: true

- name: "Config misc services(ntp, firewall)"
  shell: |
    ntpd -u ntp:ntp ; ntpq -p ; sleep 3
    sh /root/init/common/linux/firewall/firewalld/config_firewalld.sh cmds_firewalld allow

    #yast firewall services add zone=EXT service=service:avahi
    firewall-cmd --zone=public --permanent --add-service=mdns
  ignore_errors: true

#- lineinfile:
#    path: /etc/sudoers
#    state: present
#    insertafter: 'Defaults.*env_reset.*'
#    regexp: 'Defaults.*secure_path=.*'
#    line: 'Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
#  ignore_errors: true
