---

- lineinfile:
    path: /etc/csh.cshrc
    state: present
    regexp: '^setenv JAVA_HOME.*'
    line: 'setenv JAVA_HOME {{distro_pkgs.default_java_home}}'
  ignore_errors: true

- lineinfile:
    path: /etc/fstab
    state: present
    regexp: '^fdesc'
    line: 'fdesc  /dev/fd  fdescfs  rw  0  0'
  ignore_errors: true

- name: "Config misc services(ntp, firewall)"
  shell: |
    #ntpd -u ntp:ntp ; ntpq -p
    ntpdate -v -u -b us.pool.ntp.org

    pfctl -d
    sh /root/init/common/bsd/firewall/pf/pfconf.sh config_pf allow > /etc/pf.conf.new
    if [ ! -e /etc/pf.conf ] ; then cp /etc/pf.conf.new /etc/pf.conf ; fi
    pfctl -vf /etc/pf.conf ; pfctl -s info ; pfctl -s rules -a '*'

    cd /usr/bin
    for file1 in lp lpq lpr lprm ; do
      if [ -e $file1 ] ; then
        mv $file1 $file1.old ;
      fi ;
      ln -s /usr/local/bin/$file1 $file1 ;
    done
  ignore_errors: true

- shell: sysrc devfs_system_ruleset="devfsrules_system"
  ignore_errors: true

- group: name=cups gid=193 system=yes state=present
  ignore_errors: true

- user: name={{item}} groups=cups append=yes
  ignore_errors: true
  loop: [root]

- blockinfile:
    path: /etc/devfs.rules
    state: present
    marker: '#-- {mark} managed zone --'
    marker_begin: 'start'
    marker_end: 'end'
    create: yes
    block: |
      [devfsrules_system=10]
      add path 'unlpt*' group cups mode 0660
      add path 'ulpt*' group cups mode 0660
      add path 'lpt*' group cups mode 0660

      #NOTE, find USB device correspond to printer: dmesg | grep -e ugen
      #add path 'usb/X.Y.Z' group cups mode 0660
  ignore_errors: true
