---

- name: Fetch missing distribution sets (xbase*) & sysmerge updates
  shell: |
    arch=$(arch -s) ; rel=$(sysctl -n kern.osrelease)
    setVer=$(echo $rel | tr '.' '\0')
    cd /tmp
    for setX in xbase ; do
      ftp http://cdn.openbsd.org/pub/OpenBSD/${rel}/${arch}/${setX}${setVer}.tgz ;
      tar -C / -xpzf ${setX}${setVer}.tgz ;
    done
    sysmerge

- lineinfile:
    path: /etc/ksh.kshrc
    state: present
    regexp: '^export JAVA_HOME.*'
    line: 'export JAVA_HOME={{distro_pkgs.default_java_home}}'
  ignore_errors: true

- lineinfile:
    path: /etc/fstab
    state: present
    regexp: '^fdesc.*'
    line: 'fdesc  /dev/fd  fdescfs  rw  0  0'
  ignore_errors: true

- name: "Config misc services(ntp, firewall)"
  shell: |
    #ntpd -u ntp:ntp ; ntpq -p
    ntpdate -v -u -b us.pool.ntp.org

    pfctl -d
    env sed_inplace="sed -i" sh /root/init/common/bsd/firewall/pf/pfconf.sh config_pf allow > /etc/pf.conf.new
    if [ ! -e /etc/pf.conf ] ; then cp /etc/pf.conf.new /etc/pf.conf ; fi
    pfctl -vf /etc/pf.conf ; pfctl -s info ; pfctl -s rules -a '*'

    #cd /usr/bin
    #for file1 in lp lpq lpr lprm ; do
    #  if [ -e $file1 ] ; then
    #    mv $file1 $file1.old ;
    #  fi ;
    #  ln -s /usr/local/bin/$file1 $file1 ;
    #done
  ignore_errors: true

#- user: name={{item}} groups=cups append=yes
#  ignore_errors: true
#  loop: [root]
