---
# tasks file for packer

- block:
  - name: Verify minimum ansible[-core] version
    assert:
      #that: "ansible_version.full is version_compare('2.18', '>=')"
      that: "ansible_version.full is version('2.18', '>=')"
      msg: "You must update ansible[-core] to 2.18+"
  tags: always

- block:
  - name: Load OS based (using family, distribution, ...) vars file
    include_vars: '{{item}}'
    with_first_found:
      - files:
        #- "{{(ansible_facts['lsb']['id'] or ansible_facts['lsb']['codename'])|lower}}.yml"
        - "{{(ansible_facts['os_family'] or ansible_facts['distribution'])|lower}}.yml"
        - "{{{'Artix Linux': 'Artix', 'Arch Linux': 'Archlinux', 'openSUSE Tumbleweed-Slowroll': 'Suse'}.get(ansible_facts['os_family'] or ansible_facts['distribution'])|lower}}.yml"
        skip: True
  #tags: never, upgradepkgs, cmdlntools, userifc, codelab
  tags: always

- block:
  - name: Get keys from ini
    shell: sed -n '/^[a-z0-9_]*=/ s|\(.*\)=.*|\1|p' /root/scripts/distro_pkgs.ini
    ignore_errors: true
    register: keysout

  #- name: (shell cmd) Get matching key|value's from ini
  #  shell: . /root/scripts/distro_pkgs.ini ; echo ${{item}}
  #  ignore_errors: true
  #  register: inivalue
  #  loop: '{{keysout.stdout_lines}}'

  #- name: (ini values fm shell cmd) Set dictionary of variables from ini
  #  set_fact:
  #    cacheable: true
  #    distro_pkgs: '{{ distro_pkgs|default({})|combine({ item.item: item.stdout }) }}'
  #  loop: '{{inivalue.results}}'

  - name: retrieve remote ini file
    fetch: src=/root/scripts/distro_pkgs.ini dest=/tmp/
    ignore_errors: true

  #- name: (lookup:ini) Set variable from ini
  #  set_fact:
  #    cacheable: true
  #    pkgs_cmdln_tools: "{{ lookup('ini', 'pkgs_cmdln_tools type=properties file=/tmp/{{inventory_hostname}}/root/scripts/distro_pkgs.ini')|replace('\"', '')|regex_replace('\\${service_mgr:-[a-z]*}', service_mgr) }}"

  - name: (lookup:ini) Set dictionary of variables from ini
    set_fact:
      cacheable: true
      distro_pkgs: "{{ distro_pkgs|default({})|combine({item: lookup('ini', item ~ ' type=properties file=/tmp/{{inventory_hostname}}/root/scripts/distro_pkgs.ini')|replace('\"', '')|regex_replace('\\${service_mgr:-[a-z]*}', service_mgr)}) }}"
    loop: '{{keysout.stdout_lines}}'
  #- debug: var=distro_pkgs
  #tags: never, cmdlntools, userifc, codelab
  tags: >
    never, cmdlntools-00install_pkgs, cmdlntools-02toggle_svcs, cmdlntools,
    userifc-00install_pkgs, userifc-02toggle_svcs, userifc, codelab-00install_pkgs,
    codelab-02toggle_svcs, codelab
  #tags: always

- block:
  - name: "Set distribution version"
    set_fact: cacheable=true ansible_facts['distribution_version']='rolling'
    when: variant in ['archlinux']
  tags: always

- block:
  - name: "Set pkg mgr"
    set_fact: cacheable=true ansible_facts['pkg_mgr']='dnf'
    when: variant in ['mageia']
  tags: always

- import_tasks: snapshot.yml
  tags: never, snapshot

- block:
  #- set_fact: cacheable=false distrosets=["src"] # FreeBSD
  #- set_fact: cacheable=false distrosets=["xbase"] # NetBSD,OpenBSD
  - import_tasks: common/fetch_distrosets.yml
  tags: never, fetch_distrosets

- block:
  - import_tasks: upgradepkgs.yml
    tags: upgradepkgs

  - import_tasks: cmdlntools/00install_pkgs.yml
    tags: never, cmdlntools-00install_pkgs

  - import_tasks: cmdlntools/01config_sys.yml
    tags: never, cmdlntools-01config_sys

  - import_tasks: cmdlntools/02toggle_svcs.yml
    tags: never, cmdlntools-02toggle_svcs

  - block:
    #- include_tasks: cmdlntools.yml
    - include_tasks: cmdlntools/00install_pkgs.yml
    - include_tasks: cmdlntools/01config_sys.yml
    - include_tasks: cmdlntools/02toggle_svcs.yml
    tags: never, cmdlntools

  - import_tasks: userifc/00install_pkgs.yml
    tags: never, userifc-00install_pkgs

  - import_tasks: userifc/01config_sys.yml
    tags: never, userifc-01config_sys

  - import_tasks: userifc/02toggle_svcs.yml
    tags: never, userifc-02toggle_svcs

  - block:
    #- include_tasks: userifc.yml
    - include_tasks: userifc/00install_pkgs.yml
    - include_tasks: userifc/01config_sys.yml
    - include_tasks: userifc/02toggle_svcs.yml
    tags: never, userifc

  - import_tasks: codelab/00install_pkgs.yml
    tags: never, codelab-00install_pkgs

  - import_tasks: codelab/01config_sys.yml
    tags: never, codelab-01config_sys

  - import_tasks: codelab/02toggle_svcs.yml
    tags: never, codelab-02toggle_svcs

  - block:
    #- include_tasks: codelab.yml
    - include_tasks: codelab/00install_pkgs.yml
    - include_tasks: codelab/01config_sys.yml
    - include_tasks: codelab/02toggle_svcs.yml
    tags: never, codelab
