---

- block:
  - name: install nano
    package: use='{{pkg_mgr}}' name='{{pkgs_commasep}}' state=present skip_broken=true
    ignore_errors: true
    when: pkg_mgr == 'dnf'

  - name: install nano
    package: use='{{pkg_mgr}}' name='{{pkgs_commasep}}' state=present extra_args_precommand='--ignore-unknown'
    ignore_errors: true
    when: pkg_mgr == 'zypper'

  - block:
    - name: install nano
      package: use='{{pkg_mgr}}' name='{{pkgs_commasep}}' state=present
      ignore_errors: true
      register: out
    #- debug: var=out

    - name: retry failed install nano
      package: use='{{pkg_mgr}}' name='{{item}}' state=present
      ignore_errors: true
      loop: '{{pkgs_list}}'
      when: out.get('failed', false)
    when: pkg_mgr not in ['zypper', 'dnf']
  vars:
    pkgs_commasep: '{{"pkgUnknown nano pkgMissing zip".replace(" ", ",")}}'
    #pkgs_list: [pkgUnknown, nano, pkgMissing, zip]
    pkgs_list: '{{"pkgUnknown nano pkgMissing zip".split(" ")}}'
