---

- shell: |
    dnf --setopt=install_weak_deps=False config-manager --save
    dnf config-manager --dump | grep -we install_weak_deps
  ignore_errors: true

- name: "Fix text mode only grub config ; systemd set default graphical.target"
  shell: |
    systemctl set-default graphical.target

    sed -i 's|nomodeset | |' /etc/default/grub
    sed -i 's|text | |' /etc/default/grub
    . /etc/os-release
    grub2-mkconfig -o /boot/grub/grub.cfg
    grub2-mkconfig -o /boot/efi/EFI/${ID}/grub.cfg
  ignore_errors: true
