---

- block:
  - file: path=/etc/X11/xorg.conf.d state=directory
    ignore_errors: true

  - shell: "cp -an /usr/share/X11/xorg.conf.d/{{confX}} /etc/X11/xorg.conf.d/"
    ignore_errors: true
    loop: [10-evdev.conf, 40-libinput.conf]
    loop_control: {"loop_var": "confX"}

  - shell: |
      # Note, ex: dpkg-reconfigure lightdm
      # [/usr/[s]bin/[startxfce4 | startlxqt | lightdm | sddm | gdm3]
      update-alternatives --set x-session-manager $(cat /etc/X11/default-display-manager)
    ignore_errors: true
    when: service_mgr != 'systemd'

  - name: "Fix text mode only default grub config"
    replace:
      path: /etc/default/grub
      regexp: '{{item}}'
      replace: ''
    ignore_errors: true
    loop: ['nomodeset ', 'text ', 'xdriver=vesa ']

  - name: "Run grub-mkconfig"
    shell: grub-mkconfig -o /boot/grub/grub.cfg
    ignore_errors: true
