---

- stat: path=/usr/share/X11/xorg.conf.d
  ignore_errors: true
  register: xorgconfd_dir_st

- block:
  - file: path=/etc/X11/xorg.conf.d state=directory
    ignore_errors: true

  - shell: "cp -an /usr/share/X11/xorg.conf.d/{{confX}} /etc/X11/xorg.conf.d/"
    ignore_errors: true
    loop: [10-evdev.conf, 40-libinput.conf]
    loop_control: {"loop_var": "confX"}

  - lineinfile:
      path: /etc/conf.d/xdm
      state: present
      regexp: '^DISPLAYMANAGER=.*'
      line: 'DISPLAYMANAGER="sddm"'
    ignore_errors: true
    #when: ansible_facts.get('lsb', {}).get('id', None)|lower in ['artix'] and 'lxqt' == desktop
    when: service_mgr != 'systemd' and 'lxqt' == desktop

  - lineinfile:
      path: /etc/conf.d/xdm
      state: present
      regexp: '^DISPLAYMANAGER=.*'
      line: 'DISPLAYMANAGER="gdm"'
    ignore_errors: true
    #when: ansible_facts.get('lsb', {}).get('id', None)|lower in ['artix'] and 'lxqt' != desktop
    when: service_mgr != 'systemd' and 'lxqt' != desktop

  - copy:
      dest: /etc/X11/xorg.conf.d/10-modesetting.conf
      #mode: 'ugo+x'
      force: false
      content: |
        #Section "Device"
        #  Identifier "GPU0"
        #  Driver "modesetting"
        #  #BusID "PCI:0:2:0"
        #EndSection

    ignore_errors: true

  #- shell: sh /root/init/common/misc_config.sh cfg_xorgtouchpad /etc/X11/xorg.conf.d
  #  ignore_errors: true

  - lineinfile:
      path: '/etc/X11/xorg.conf.d/{{confX}}'
      state: present
      insertafter: '^[^#]\s*MatchIsTouchpad.*'
      regexp: '.*Option "Tapping" "on".*'
      line: '       Option "Tapping" "on"'
    ignore_errors: true
    loop: [10-evdev.conf, 40-libinput.conf]
    loop_control: {"loop_var": "confX"}
  when: xorgconfd_dir_st.stat.exists and xorgconfd_dir_st.stat.isdir

- block:
  - name: "Fix text mode only default grub config"
    replace:
      path: /etc/default/grub
      regexp: '{{item}}'
      replace: ''
    ignore_errors: true
    loop: [' nomodeset', ' text', ' xdriver=vesa']

  - name: "Run grub-mkconfig"
    shell: grub-mkconfig -o /boot/grub/grub.cfg
    ignore_errors: true
