---

- block:
  - file: path=/etc/X11/xorg.conf.d state=directory
    ignore_errors: true

  - shell: "cp -an /usr/share/X11/xorg.conf.d/{{confX}} /etc/X11/xorg.conf.d/"
    ignore_errors: true
    loop: [10-evdev.conf, 40-libinput.conf]
    loop_control: {"loop_var": "confX"}

  - lineinfile:
      path: /etc/conf.d/xdm
      state: present
      regexp: '^DISPLAYMANAGER=.*'
      line: 'DISPLAYMANAGER="sddm"'
    ignore_errors: true
    #when: ansible_facts.get('lsb', {}).get('id', None)|lower in ['artix'] and 'lxqt' == desktop
    when: service_mgr != 'systemd' and 'lxqt' == desktop

  - lineinfile:
      path: /etc/conf.d/xdm
      state: present
      regexp: '^DISPLAYMANAGER=.*'
      line: 'DISPLAYMANAGER="gdm"'
    ignore_errors: true
    #when: ansible_facts.get('lsb', {}).get('id', None)|lower in ['artix'] and 'lxqt' != desktop
    when: service_mgr != 'systemd' and 'lxqt' != desktop

  - name: "Fix text mode only default grub config"
    replace:
      path: /etc/default/grub
      regexp: '{{item}}'
      replace: ''
    ignore_errors: true
    loop: ['nomodeset ', 'text ', 'xdriver=vesa ']

  - name: "Run grub-mkconfig"
    shell: grub-mkconfig -o /boot/grub/grub.cfg
    ignore_errors: true
