---

- block:
  - file: path=/etc/X11/xorg.conf.d state=directory
    ignore_errors: true

  - shell: "cp -an /usr/share/X11/xorg.conf.d/{{confX}} /etc/X11/xorg.conf.d/"
    ignore_errors: true
    loop: [10-evdev.conf, 40-libinput.conf]
    loop_control: {"loop_var": "confX"}

  - name: "Fix text mode only default grub config"
    replace:
      path: /etc/default/grub
      regexp: '{{item}}'
      replace: ''
    ignore_errors: true
    loop: ['nomodeset ', 'text ', 'xdriver=vesa ']

  - name: "Run grub2-mkconfig"
    shell: |
      . /etc/os-release
      grub2-mkconfig -o /boot/grub/grub.cfg
      grub2-mkconfig -o /boot/efi/EFI/${ID}/grub.cfg
    ignore_errors: true
