# archlinux/{distro_pkgs.ini,distro_pkgmgr_funcs.sh}
# to use variables|functions, source these file(s):
# source distro_pkgs.ini ; source distro_pkgmgr_funcs.sh
# ${pkgmgr_install} ${pkgs_cmdln_tools} 2> /tmp/pkgsInstall_stderr.txt | tee /tmp/pkgsInstall_stdout.txt

pkgs_cmdln_extras="ledger msmtp-mta isync mutt s-nail transmission-cli rtorrent irssi finch rclone cmus"
# todotxt(AUR) fdm
## pip install [--break-system-packages] --user xx: khal khard vdirsyncer offlineimap topydo beancount getmail6

pkgs_filesys_utils="dosfstools gptfdisk parted fsarchiver exfat-utils"

# nfs-server
services_enabled="syslog-ng openntpd cronie opensmtpd dbus firewalld avahi-daemon NetworkManager rpcbind rpc-statd statd nfs-utils nfs-client cups cupsd cups-browsed"
services_disabled="ipset ip6tables iptables freshclam clamd dhcpcd wpa_supplicant"
pkgs_cmdln_tools="dbus-${service_mgr:-runit} dbus openntpd-${service_mgr:-runit} openntpd cronie-${service_mgr:-runit} cronie syslog-ng-${service_mgr:-runit} syslog-ng opensmtpd-${service_mgr:-runit} opensmtpd s-nail firewalld-${service_mgr:-runit} firewalld networkmanager-${service_mgr:-runit} networkmanager clamav-${service_mgr:-runit} clamav base-devel lsb-release man-db man-pages sudo bash mc rlwrap nano curl wget aria2 gnu-netcat bzip2 zip unzip p7zip gnupg pass keychain openssl gnutls w3m cyrus-sasl qpdf sqlite git mercurial nmap screen tmux avahi-${service_mgr:-runit} nss-mdns rpcbind-${service_mgr:-runit} rpcbind nfs-utils-${service_mgr:-runit} nfs-utils cups-${service_mgr:-runit} cups-pdf rsync-${service_mgr:-runit} rsync"
# tcpdump


xorg_pkg="xorg-server"
pkgs_xorg_addons="xorg xf86-video-vesa xf86-video-intel xf86-input-libinput xf86-input-evdev xterm xscreensaver"

# seatd
uiservices_enabled_kde="dbus sddm display-manager"
uiservices_disabled_kde=""
# [seatd-${service_mgr:-runit} seatd | polkit]
pkgs_deskenv_kde="dbus-${service_mgr:-runit} dbus xdg-utils xdg-user-dirs breeze-icons ttf-dejavu sddm-${service_mgr:-runit} sddm plasma konsole dolphin"
# kate conky

# seatd
uiservices_enabled_xfce="dbus gdm display-manager"
uiservices_disabled_xfce=""
# [seatd-${service_mgr:-runit} seatd | polkit]
pkgs_deskenv_xfce="dbus-${service_mgr:-runit} dbus xdg-utils xdg-user-dirs ttf-dejavu gdm-${service_mgr:-runit} gdm gvfs xfce4"
# conky

# seatd
uiservices_enabled_lxqt="dbus sddm display-manager"
uiservices_disabled_lxqt=""
# [seatd-${service_mgr:-runit} seatd | polkit]
pkgs_deskenv_lxqt="dbus-${service_mgr:-runit} dbus xdg-utils xdg-user-dirs breeze-icons ttf-dejavu sddm-${service_mgr:-runit} sddm gvfs lxqt"
# menumaker conky


# possibly extra Qt:Gtk deskenv apps
# ----------------------------------------
# (disk utils) partitionmanager:gparted
# (ifc connect) cmst:wicd bluez-qt:blueman
# (editors, office apps) :geany libreoffice :gnucash
# (file share) transmission-qt:transmission-gtk luckybackup:grsync
# (archivers) ark:xarchiver
# (clipboard tool) qlipper:parcellite
# (crypt utils) keepassxc:keepass2 qtpass: kwalletmanager:seahorse
# (browser) :chromium falkon:firefox-esr
# (email) :thunderbird
# (print utils) skanlite:simple-scan qpdfview:epdfview
# (db utils) sqlitebrowser:
# (IM-IRC) quassel:hexchat :pidgin
# (vcs gui) qgit:gitg tortoisehg:
# (traffic util) nmapsi4:zenmap wireshark
# (media plyr) clementine:gmusicbrowser smplayer:totem
# (audio tool) pavucontrol-qt:pavucontrol k3b:brasero
# (image tool) lximage-qt:gpicview :gimp
# (webcam tool) kamoso:guvcview
# (PIM tools) :gsimplecal :orage
# (ebook utils) calibre: okular:fbreader


# addons browser: AdBlock Plus, HTTPS Everywhere, uBlock Origin, NoScript,
#   User-Agent Switcher

# addons thunderbird 78+: Manually sort folders, Remove Duplicate Messages,
#   Provider f/CalDAV & CardDAV, TbSync, ? ImportExportTools NG, ? TorBirdy


labservices_enabled="dbus"
labservices_disabled=""
#(userifc)# use OS package manager to install: python-gobject
#  python-pyqt5 pyside2 python-wxpython
#(crypto)# use OS package manager to install: python-gpgme
pkgs_lang_py="dbus-${service_mgr:-runit} dbus xorg-xauth xorg-xhost python-pip python-setuptools"
# pychecker jython

lang_c_userifc="ncurses tcl tk gtk3"
# "qt5-base wxwidgets-gtk3"
lang_c_crypto="libgcrypt openssl gnutls mbedtls gpgme"
# ""
lang_c_dbase="libdbi-drivers sqlite sqlite-jdbc postgresql mariadb hiredis mongo-c-driver"
# ""
lang_c_network="curl"
# ""
pkgs_lang_c="dbus-${service_mgr:-runit} dbus xorg-xauth xorg-xhost cmake automake gdb pkgconf splint clang llvm check cunit gcc-fortran lldb swig json-glib yajl"
# dnld & compile: log4c
# ddd valgrind doxygen ruby-rake premake cppcheck bcunit
## pip install [--break-system-packages] --user xx: meson ninja scons

#(dbase)# use OS package manager to install: ??
#
pkgs_lang_java="dbus-${service_mgr:-runit} dbus xorg-xauth xorg-xhost jdk11-openjdk"
# apache-ant maven gradle
#default_path_to_fx="[/usr/lib/jvm|/opt]/java-[11]-openjfx/lib"
# dnld: https://download2.gluonhq.com/openjfx/[11]/openjfx-[11]_[linux]-[x64]_bin-[sdk|jmods].zip

pkgs_lang_cs="dbus-${service_mgr:-runit} dbus xorg-xauth xorg-xhost dotnet-core mono mono-msbuild fsharp"
# osslsigncode src dnld: https://github.com/mtrojnar/osslsigncode/archive/refs/tags/[X.Y].zip
## NOTE: missing *.dll(s) errors - edit [/usr/local]/etc/mono/config
##  example: libgobject-2.0 -> libgobject-2.0-0.dll
# dnld: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
# dotnet-sdk gtk-sharp-3

pkgs_lang_fs="dbus-${service_mgr:-runit} dbus xorg-xauth xorg-xhost dotnet-core mono mono-msbuild fsharp"


pkgs_lang_rb="ruby"
# jruby

pkgs_lang_go="go gpm"

pkgs_lang_rs="rust"

pkgs_lang_scala="dbus-${service_mgr:-runit} dbus xorg-xauth xorg-xhost jdk11-openjdk"
# apache-ant
pkgs_lang_clj=""
# clojure leiningen

pkgs_lang_hs="ghc stack"

pkgs_lang_ml="ocaml opam dune ocamlbuild ocaml-findlib"

pkgs_lang_scm="gauche guile"

pkgs_lang_lisp="sbcl clisp"

pkgs_lang_swift="libbsd libedit icu ncurses"
# dnld: https://download.swift.org/swift-[5.6]-release/[amazonlinux2][-aarch64]/swift-[5.6]-RELEASE/swift-[5.6]-RELEASE-[amazonlinux2][-aarch64].tar.gz[.sig]
