---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'openrc'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'apk'}}"
pkgclean_cmd: apk -v cache clean
pkgrepos_cmd: tail -vn+1 /etc/apk/repositories | grep -ve "^#"
pkgoutdated_cmd: apk upgrade --simulate
pkglocks_cmd: true

firewall_tool: firewalld
smtp_daemon: smtpd
