---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'systemd'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'pacman'}}"
pkgclean_cmd: pacman -Sc --noconfirm
pkgrepos_cmd: tail -vn+1 /etc/pacman.conf | grep -ve "^#" -ve "^\s*$" ; tail -vn+1 /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-arch | grep -ve "^#" | head -n10
pkgoutdated_cmd: pacman -Qqu
pkglocks_cmd: grep -e '^IgnorePkg' /etc/pacman.conf

idsuffix_cmd: test -e /var/lib/dbus/machine-id && cat /var/lib/dbus/machine-id | cut -b29-32 || echo 0000

firewall_tool: firewalld
smtp_daemon: opensmtpd
