---
# Non-default OS based (using family, distribution, ...) vars file

variant: "{{({'Artix': 'Archlinux'}.get(ansible_facts['lsb']['id']) or ansible_facts.get('distribution') or ansible_facts.get('os_family'))|lower}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'pacman'}}"
pkgupgd_params: {"update_cache": yes, "upgrade": yes, "use": "{{pkg_mgr}}"}
