---
# vars file for packer

variant: "{{(ansible_facts.get('os_family') or ansible_facts.get('distribution'))|lower}}"
pkgupgd_params: {"update_cache": yes, "upgrade": yes}

hostname_chgfiles: [/etc/hosts, /etc/hostname]
firewall_chgfiles: [/etc/nftables.conf, /etc/nftables/outallow_nftables.conf,
  /etc/nftables/outdeny_nftables.conf]
skeldir_par: /etc/skel
skel_dirs: [/etc/skel/.gnupg, /etc/skel/.pki, /etc/skel/.ssh]
skelmaps_srcdest: [{'srcskel': '_gnupg/*', 'destskel': '.gnupg/'},
  {'srcskel': '_pki/*', 'destskel': '.pki/'},
  {'srcskel': '_ssh/*', 'destskel': '.ssh/'},
  {'srcskel': '_gitconfig', 'destskel': '.gitconfig'},
  {'srcskel': '_hgrc', 'destskel': '.hgrc'}]
sudoers_file: /etc/sudoers
sudoers_group: wheel
skeldir_ssh: /etc/skel/.ssh
skel_shellrc: /etc/skel/.bashrc
sharednode: "{{lookup('env', 'SHARED_NODE') or 'localhost.local'}}"
printname: "{{lookup('env', 'PRINT_NAME') or 'printer1'}}"
etcdir_cups: /etc/cups
cupsdir_ppd: /usr/share/cups/model
