---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'bsdinit'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'pkgin'}}"
pkgclean_cmd: pkgin -y clean
pkgrepos_cmd: tail -vn+1 /usr/pkg/etc/pkgin/repositories.conf | grep -ve "^#"
pkgoutdated_cmd: pkgin -l\< list
#pkglocks_cmd:

#idsuffix_cmd: (/sbin/sysctl -n machdep.dmi.system-uuid || printf '0%.0s' {1..36}) | cut -b33-36
idsuffix_cmd: test -n "`/sbin/sysctl -n machdep.dmi.system-uuid`" && /sbin/sysctl -n machdep.dmi.system-uuid | cut -b33-36 || echo 0000

firewall_tool: pf
smtp_daemon: postfix
hostname_chgfiles: [/etc/hosts, /etc/rc.conf]
sudoersd_dir: /usr/pkg/etc/sudoers.d
#skel_shellrc: /etc/skel/.cshrc
skel_shellrc: /etc/skel/.shrc
etcdir_cups: /usr/pkg/etc/cups
cupsdir_ppd: /usr/pkg/share/cups/model

xorgconfd_dir: /usr/pk/etc/X11/xorg.conf.d
#etcdir_xdg: /usr/pkg/etc/xdg
