---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'bsdinit'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'openbsd_pkg'}}"
pkgclean_cmd: true
pkgrepos_cmd: tail -n+1 . /etc/installurl | grep -ve "^#"
pkgoutdated_cmd: pkg_add -n -u
#pkglocks_cmd:

#idsuffix_cmd: (sysctl -n hw.uuid || printf '0%.0s' {1..36}) | cut -b33-36
#idsuffix_cmd: test -n "`sysctl -n hw.uuid`" && sysctl -n hw.uuid | cut -b33-36 || echo 0000

firewall_tool: pf
smtp_daemon: smtpd
hostname_chgfiles: [/etc/hosts, /etc/myname]
#skel_shellrc: /etc/skel/.cshrc
skel_shellrc: /etc/skel/.shrc
cupsdir_ppd: /usr/local/share/cups/model

#etcdir_xdg: /etc/xdg
