---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'sysvinit'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'apt_rpm'}}"
pkgclean_cmd: apt-get -y clean
pkgrepos_cmd: tail -vn+1 /etc/apt/sources.list /etc/apt/sources.list.d/*.list | grep -ve "^#"
pkgoutdated_cmd: apt-get --simulate -y dist-upgrade
pkglocks_cmd: grep -e '^Hold' /etc/apt/apt.conf

idsuffix_cmd: test -e /var/lib/dbus/machine-id && cat /var/lib/dbus/machine-id | cut -b29-32 || echo 0000

firewall_tool: iptables
smtp_daemon: postfix
hostname_chgfiles: [/etc/hosts, /etc/hostname, /etc/sysconfig/network]
