---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'systemd'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'dnf'}}"
pkgclean_cmd: dnf -C -y clean all
pkgrepos_cmd: dnf -C repolist -v --enabled | grep -e "Repo-id" -e "Repo-name" -e "Repo-mirrors" -e "Repo-baseurl"
pkgoutdated_cmd: dnf -C -y check-update
pkglocks_cmd: dnf -C -y versionlock list

firewall_tool: firewalld
smtp_daemon: postfix
hostname_chgfiles: [/etc/hosts, /etc/hostname, /etc/sysconfig/network]
