---
# Non-default OS based (using family, distribution, ...) vars file

variant: "{{ansible_facts.get('os_family', 'redhat')|lower}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'dnf'}}"
pkgupgd_params: {"update_cache": yes, "state": "latest", "use": "{{pkg_mgr}}"}

idsuffix_cmd: cat /var/lib/dbus/machine-id | cut -b29-32
services_enabled: [chronyd, firewalld, systemd-udevd, dbus, avahi-daemon, nfs-utils, cups, cups-browsed]
services_disabled: [ipset, ip6tables, iptables, clamav-freshclam, clamd@]

hostname_chgfiles: [/etc/hostname, /etc/hosts, /etc/sysconfig/network]
firewall_chgfiles: []
sudoers_group: wheel
cupsdir_ppd: /usr/share/cups/model

uiservices_enabled: [dbus, display-manager]
