---
# Non-default OS based (using family, distribution, ...) vars file

pkgupgd_params: {"update_cache": yes, "state": "dist-upgrade", "name": "*"}

idsuffix_cmd: cat /var/lib/dbus/machine-id | cut -b29-32
services_enabled: [ntpd, firewalld, dbus, avahi-daemon, cups, cups-browsed]
services_disabled: [ipset, ip6tables, iptables, freshclam, clamd]

hostname_chgfiles: [/etc/hosts, /etc/hostname, /etc/sysconfig/network]
firewall_chgfiles: []
sudoers_group: wheel
cupsdir_ppd: /usr/share/cups/model
