---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'systemd'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'zypper'}}"
pkgclean_cmd: zypper --no-refresh --non-interactive clean --all
pkgrepos_cmd: zypper --no-refresh repos -u
pkgoutdated_cmd: zypper --no-refresh --non-interactive list-updates --all
pkglocks_cmd: zypper locks

firewall_tool: firewalld
smtp_daemon: postfix
hostname_chgfiles: [/etc/hosts, /etc/hostname, /etc/sysconfig/network]
