---
# Non-default OS based (using family, distribution, ...) vars file

variant: "{{(ansible_facts.get('os_family') or ansible_facts.get('distribution') or ansible_facts.get('lsb')['codename'])|lower}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'xbps'}}"
pkgupgd_params: {"update_cache": yes, "upgrade": yes, "use": "{{pkg_mgr}}"}

idsuffix_cmd: cat /var/lib/dbus/machine-id | cut -b29-32
services_enabled: [ntpd, nftables, udevd, dbus, avahi-daemon, rpcbind, cupsd]
services_disabled: [ipset, ip6tables, iptables, clamd]
