---
# Non-default OS based (using family, distribution, ...) vars file

service_mgr: "{{ansible_facts.get('service_mgr') or 'runit'}}"
pkg_mgr: "{{ansible_facts.get('pkg_mgr') or 'xbps'}}"
pkgclean_cmd: xbps-remove -Ooy
pkgrepos_cmd: xbps-query -L
pkgoutdated_cmd: xbps-install --dry-run -u
pkglocks_cmd: xbps-query --list-hold-pkgs

#idsuffix_cmd: (cat /var/lib/dbus/machine-id || printf '0%.0s' {1..32}) | cut -b29-32
idsuffix_cmd: test -e /var/lib/dbus/machine-id && cat /var/lib/dbus/machine-id | cut -b29-32 || echo 0000

firewall_tool: nftables
smtp_daemon: opensmtpd
