---

- block:
  - copy:
      src: /usr/share/doc/avahi/ssh.service
      dest: /etc/avahi/services/
      remote_src: true
    ignore_errors: true

  - replace:
      path: /etc/avahi/avahi-daemon.conf
      regexp: 'use-ipv6=yes'
      replace: 'use-ipv6=no'
    ignore_errors: true

# for runit service ops w/ Ansible,Saltstack
- file: src={{item.srcX}} dest={{item.destX}} state=link
  ignore_errors: true
  loop: [{srcX: '/etc/runit/sv', destX: '/etc/sv'}
        #, {srcX: '/etc/runit/runsvdir/default', destX: '/var/service'}
        , {srcX: '/run/runit/service', destX: '/var/service'}
        ]
  when: service_mgr == 'runit'

# Undo syslog-ng default logging disabled (comments: filter,destination)
- block:
  - copy:
      src: /etc/syslog-ng/syslog-ng.conf
      dest: /etc/syslog-ng/syslog-ng.conf.orig
      remote_src: true
      force: false
    ignore_errors: true

  - replace:
      path: /etc/syslog-ng/syslog-ng.conf
      regexp: '^(.*)(#\s*)({{item}}.*)$'
      replace: '\1\2\3\n\1\3'
    ignore_errors: true
    loop: [filter, destination]

#- file: path=/var/lib/clamav state=directory recurse=true owner=clamav group=clamav
#  ignore_errors: true

#- file: path=/var/lib/clamav/clamd.sock state=touch owner=clamav group=clamav
#  ignore_errors: true

#- lineinfile:
#    path: /etc/sudoers
#    state: present
#    regexp: 'Defaults.*secure_path=.*'
#    line: 'Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
#  ignore_errors: true
