---

#- block:
#  - set_fact: cacheable=false distrosets=["src"]
#  - include_tasks: common/fetch_distrosets.yml

- file: path={{item}} state=touch
  loop: [/boot/loader.conf, /etc/rc.conf]

- community.general.sysrc: name={{item.flagX}} value='{{item.valX}}' state={{item.stateX}}
  ignore_errors: true
  loop: [{'flagX': 'devfs_system_ruleset', 'valX': 'devfsrules_system', 'stateX': 'present'}
        , {'flagX': 'syslogd_flags', 'valX': '-ss', 'stateX': 'present'}
        , {'flagX': 'ntpd_sync_on_start', 'valX': 'YES', 'stateX': 'present'}
        , {'flagX': 'cron_flags', 'valX': '-J 60 -j 60', 'stateX': 'present'}
        #, {'flagX': 'anacron_flags', 'valX': '-s', 'stateX': 'value_present'}
        #, {'flagX': 'mountd_flags', 'valX': '-r', 'stateX': 'present'}
        ]

#- community.general.sysrc:
#    name: anticongestion_sleeptime
#    value: 3600
#    state: present
#    path: /etc/periodic.conf
#  ignore_errors: true

- community.general.sysrc: name={{item.flagX}} value='{{item.valX}}' state=present path=/etc/periodic.conf
  ignore_errors: true
  loop: [{'flagX': 'daily_clean_tmps_enable', 'valX': 'NO'}
        #, {'flagX': 'daily_clean_tmps_days', 'valX': '15'}
        , {'flagX': 'daily_status_ntpd_enable', 'valX': 'YES'}
        , {'flagX': 'daily_status_disks_df_flags', 'valX': '-lhT -c'}
        , {'flagX': 'daily_output', 'valX': ''}
        , {'flagX': 'weekly_output', 'valX': ''}
        , {'flagX': 'monthly_output', 'valX': ''}
        , {'flagX': 'daily_status_security_output', 'valX': '/var/log/security.out'}
        ]

- blockinfile:
    path: /etc/devfs.rules
    state: present
    marker: '#-- {mark} managed zone --'
    marker_begin: 'start'
    marker_end: 'end'
    create: true
    block: |
      [devfsrules_system=10]
      add path 'unlpt*' group cups mode 0660
      add path 'ulpt*' group cups mode 0660
      add path 'lpt*' group cups mode 0660

      #NOTE, find USB device correspond to printer: dmesg | grep -e ugen
      #add path 'usb/X.Y.Z' group cups mode 0660
  ignore_errors: true

- block:
  - group: name=cups gid=193 system=true state=present
    ignore_errors: true

  - user: name={{item}} groups=cups append=true
    ignore_errors: true
    loop: [root]

  - copy: remote_src=true src=/usr/bin/{{item}} dest=/usr/bin/{{item}}.old
    ignore_errors: true
    loop: [lp, lpq, lpr, lprm]

  - file: path=/usr/bin/{{item}} state=absent
    ignore_errors: true
    loop: [lp, lpq, lpr, lprm]

  - file: src=/usr/pkg/bin/{{item}} dest=/usr/bin/{{item}} state=link
    ignore_errors: true
    loop: [lp, lpq, lpr, lprm]
    when: ansible_facts.get('system')|lower == 'netbsd'

  - file: src=/usr/local/bin/{{item}} dest=/usr/bin/{{item}} state=link
    ignore_errors: true
    loop: [lp, lpq, lpr, lprm]
    when: ansible_facts.get('system')|lower in ['freebsd', 'openbsd']
#  when: ansible_facts.get('system')|lower in ['freebsd', 'netbsd', 'openbsd']
