---

#- file: path=/var/lib/clamav state=directory recurse=true owner=clamav group=clamav
#  ignore_errors: true

#- file: path=/var/lib/clamav/clamd.sock state=touch owner=clamav group=clamav
#  ignore_errors: true

#- block:
#  - replace:
#      path: '{{item}}'
#      regexp: '^Example'
#      replace: '#Example'
#    ignore_errors: true
#    loop: [/etc/freshclam.conf, /etc/clamd.d/scan.conf]
#
#  - replace:
#      path: /etc/clamd.d/scan.conf
#      regexp: '^#\s*LocalSocket'
#      replace: 'LocalSocket'
#    ignore_errors: true

#- lineinfile:
#    path: /etc/sudoers
#    state: present
#    insertafter: 'Defaults.*env_reset.*'
#    regexp: 'Defaults.*secure_path=.*'
#    line: 'Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
#  ignore_errors: true
