---

- file: path=/var/log/messages state=touch

#- file: path=/var/lib/clamav state=directory recurse=true owner=clamav group=clamav
#  ignore_errors: true

#- file: path=/var/lib/clamav/clamd.sock state=touch owner=clamav group=clamav
#  ignore_errors: true

#- lineinfile:
#    path: /etc/sudoers
#    state: present
#    insertafter: 'Defaults.*env_reset.*'
#    regexp: 'Defaults.*secure_path=.*'
#    line: 'Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
#  ignore_errors: true
