---

- block:
  - package: use='{{pkg_mgr}}' name='socklog,socklog-void' state=absent
    ignore_errors: true

  - file: path=/var/log/socklog state=absent
    ignore_errors: true

- lineinfile:
    path: /etc/rc.local
    state: present
    mode: 'ugo+x'
    regexp: '.*dbus-uuidgen.*'
    #line: '/usr/bin/dbus-uuidgen --ensure=/etc/machine-id'
    line: '/usr/bin/dbus-uuidgen --ensure'
  ignore_errors: true

#- file: path=/var/lib/clamav state=directory recurse=true owner=clamav group=clamav
#  ignore_errors: true

#- file: path=/var/lib/clamav/clamd.sock state=touch owner=clamav group=clamav
#  ignore_errors: true

#- lineinfile:
#    path: /etc/sudoers
#    state: present
#    regexp: 'Defaults.*secure_path=.*'
#    line: 'Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
#  ignore_errors: true
