---

- copy:
    src: /root/init/common/smtp/linux/mail.rc.sample
    dest: /etc/mail.rc
    remote_src: true
    force: false
  ignore_errors: true

## #NOTE, nftables lacking sysvinit support
#- copy:
#    dest: /etc/init.d/nftables
#    src: /usr/share/doc/nftables/examples/sysvinit/nftables.init
#    remote_src: true
#    mode: 'ugo+x'
#  ignore_errors: true

#- lineinfile:
#    path: /etc/network/if-pre-up.d/nftables
#    create: yes
#    mode: '+x'
#    regexp: '{{item.rexp}}'
#    line: '{{item.line}}'
#  ignore_errors: true
#  loop: [{rexp: '^#!/bin/sh.*', line: '#!/bin/sh'}
#    , {rexp: '.*/sbin/nft.*', line: '/usr/bin/env nft -f /etc/nftables.conf'}
#    ]

#- file: path=/var/lib/clamav state=directory recurse=true owner=clamav group=clamav
#  ignore_errors: true

#- file: path=/var/lib/clamav/clamd.sock state=touch owner=clamav group=clamav
#  ignore_errors: true

- lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: 'Defaults.*env_reset.*'
    regexp: 'Defaults.*secure_path=.*'
    line: 'Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
  ignore_errors: true
