# alpine/{distro_pkgs.ini,distro_pkgmgr_funcs.sh}
# to use variables|functions, source these file(s):
# source distro_pkgs.ini ; source distro_pkgmgr_funcs.sh
# ${pkgmgr_install} ${pkgs_cmdln_tools} 2> /tmp/pkgsInstall_stderr.txt | tee /tmp/pkgsInstall_stdout.txt

pkgs_cmdln_extras="todo.txt-cli ledger msmtp isync mutt s-nail transmission-cli rtorrent irssi finch rclone cmus"
# fdm
## pip install [--break-system-packages] --user xx: khal khard vdirsyncer offlineimap topydo beancount getmail6

pkgs_filesys_utils="cryptsetup dosfstools sgdisk parted fsarchiver fuse-exfat exfat-utils"

services_enabled="udev udev-trigger udev-settle udev-postmount rsyslog openntpd cronie smtpd dbus elogind firewalld avahi-daemon networkmanager rpcbind nfsclient cupsd"
services_disabled="syslog crond ipset ip6tables iptables freshclam clamd dhcpcd"
pkgs_cmdln_tools="dbus dbus-openrc eudev eudev-openrc udev-init-scripts openntpd openntpd-openrc cronie cronie-openrc rsyslog rsyslog-openrc opensmtpd opensmtpd-openrc s-nail elogind elogind-openrc logrotate firewalld firewalld-openrc networkmanager-cli networkmanager-openrc clamav clamav-daemon clamav-daemon-openrc freshclam freshclam-openrc lsb-release-minimal sudo python3 bash file mc nano curl wget aria2 netcat-openbsd bzip2 zip unzip p7zip gnupg pass keychain openssl gnutls-utils w3m qpdf sqlite git mercurial tcpdump nmap dialog screen tmux nss-dev nss-tools avahi avahi-tools avahi-openrc nfs-utils nfs-utils-openrc rpcbind-openrc cups-client cups cups-openrc rsync rsync-openrc"
# cups-pdf


pkgs_displaysvr="xorg-server xf86-video-vesa xf86-video-intel xf86-input-libinput xf86-input-evdev xterm xdg-user-dirs xdg-utils xscreensaver"

# polkit
uiservices_enabled_xfce="dbus polkit gdm"
uiservices_disabled_xfce=""
pkgs_deskenv_xfce="dbus dbus-openrc polkit gdm gdm-openrc xfce4-terminal xfce-polkit xfce4 conky"

# polkit
uiservices_enabled_lxqt="dbus polkit sddm"
uiservices_disabled_lxqt=""
pkgs_deskenv_lxqt="dbus dbus-openrc polkit sddm sddm-openrc breeze-icons obconf-qt gvfs lxqt-desktop lximage-qt conky"
# pavucontrol-qt nm-tray

# possibly extra Qt:Gtk deskenv apps
# ----------------------------------------
# (disk utils) partitionmanager:gparted
# (ifc connect) cmst:wicd bluez-qt:blueman
# (editors, office apps) :geany libreoffice :gnucash
# (file share) transmission-qt:transmission-gtk luckybackup:grsync
# (archivers) ark:xarchiver
# (clipboard tool) qlipper:parcellite
# (crypt utils) keepassxc:keepass2 qtpass: kwalletmanager:seahorse
# (browser) :chromium falkon:firefox-esr
# (email) :thunderbird
# (print utils) skanlite:simple-scan qpdfview:epdfview
# (db utils) sqlitebrowser:
# (IM-IRC) quassel:hexchat :pidgin
# (vcs gui) qgit:gitg tortoisehg:
# (traffic util) nmapsi4:zenmap wireshark
# (media plyr) clementine:gmusicbrowser smplayer:totem
# (audio tool) pavucontrol-qt:pavucontrol k3b:brasero
# (image tool) lximage-qt:gpicview :gimp
# (webcam tool) kamoso:guvcview
# (PIM tools) :gsimplecal :orage
# (ebook utils) calibre: okular:fbreader


# addons browser: AdBlock Plus, HTTPS Everywhere, uBlock Origin, NoScript,
#   User-Agent Switcher

# addons thunderbird 78+: Manually sort folders, Remove Duplicate Messages,
#   Provider f/CalDAV & CardDAV, TbSync, ? ImportExportTools NG, ? TorBirdy


labservices_enabled="dbus"
labservices_disabled=""
pkgs_lang_py="dbus dbus-openrc xauth xterm py3-pip"

pkgs_lang_c="dbus dbus-openrc"
# ddd

pkgs_lang_java="dbus dbus-openrc"
