# void/{distro_pkgs.ini,distro_pkgmgr_funcs.sh}
# to use variables|functions, source these file(s):
# source distro_pkgs.ini ; source distro_pkgmgr_funcs.sh
# ${pkgmgr_install} ${pkgs_cmdln_tools} 2> /tmp/pkgsInstall_stderr.txt | tee /tmp/pkgsInstall_stdout.txt

pkgs_cmdln_extras="ledger msmtp isync mutt s-nail transmission rtorrent irssi finch rclone cmus"
# todotxt fdm
## pip install [--break-system-packages] --user xx: khal khard vdirsyncer offlineimap topydo beancount getmail6

pkgs_emulation_utils="edk2-ovmf qemu-system-amd64 qemu-user-amd64 qemu-system-aarch64 qemu-user-aarch64 qemu-img qemu-tools qemu-doc incus dnsmasq"
# ansible-core salt packer

pkgs_filesys_utils="dosfstools gptfdisk parted fsarchiver fuse-exfat"

services_enabled="rsyslogd openntpd crond opensmtpd dbus elogind nftables avahi-daemon NetworkManager rpcbind statd netmount cupsd"
services_disabled="nanoklogd socklog-unix ipset ip6tables iptables clamd wpa_supplicant dhcpcd"
pkgs_cmdln_tools="dbus openntpd cronie rsyslog logrotate opensmtpd s-nail elogind nftables NetworkManager clamav sudo python3 bash mc rlwrap nano curl wget aria2 netcat bzip2 zip unzip 7zip xz gnupg pass keychain openssl gnutls w3m cyrus-sasl qpdf sqlite git mercurial tcpdump nmap screen tmux avahi-utils nss-mdns nfs-utils sv-netmount cups cups-pdf cups-browsed rsync"


pkgs_displaysvr="xorg xf86-video-vesa xf86-video-intel xf86-input-libinput xf86-input-evdev xterm xdg-user-dirs xdg-utils xscreensaver dejavu-fonts-ttf"

uiservices_enabled_xfce="dbus polkitd gdm"
uiservices_disabled_xfce=""
pkgs_deskenv_xfce="dbus polkit gdm gvfs xfce4 conky network-manager-applet"

uiservices_enabled_lxqt="dbus polkitd sddm"
uiservices_disabled_lxqt=""
pkgs_deskenv_lxqt="dbus polkit sddm breeze-icons obconf-qt menumaker gvfs lxqt conky nm-tray"


# possibly extra Qt:Gtk deskenv apps
# ----------------------------------------
# (disk utils) partitionmanager:gparted
# (ifc connect) cmst:wicd bluez-qt:blueman
# (editors, office apps) :geany libreoffice :gnucash
# (file share) transmission-qt:transmission-gtk luckybackup:grsync
# (archivers) ark:xarchiver
# (clipboard tool) qlipper:parcellite
# (crypt utils) keepassxc:keepass2 qtpass: kwalletmanager:seahorse
# (browser) :chromium falkon:firefox-esr
# (email) :thunderbird
# (print utils) skanlite:simple-scan qpdfview:epdfview
# (db utils) sqlitebrowser:
# (IM-IRC) quassel:hexchat :pidgin
# (vcs gui) qgit:gitg tortoisehg:
# (traffic util) nmapsi4:zenmap wireshark
# (media plyr) clementine:gmusicbrowser smplayer:totem
# (audio tool) pavucontrol-qt:pavucontrol k3b:brasero
# (image tool) lximage-qt:gpicview :gimp
# (webcam tool) kamoso:guvcview
# (PIM tools) :gsimplecal :orage
# (ebook utils) calibre: okular:fbreader


# addons browser: AdBlock Plus, HTTPS Everywhere, uBlock Origin, NoScript,
#   User-Agent Switcher

# addons thunderbird 78+: Manually sort folders, Remove Duplicate Messages,
#   Provider f/CalDAV & CardDAV, TbSync, ? ImportExportTools NG, ? TorBirdy


labservices_enabled="dbus"
labservices_disabled=""
pkgs_lang_py="dbus xauth xterm python3-pip python3-setuptools"
# python3-gobject-devel python3-tkinter python3-PyQt5 python3-pyside2 wxPython4

lang_c_userifc="ncurses-devel tcl-devel tk-devel gtk+3-devel"
# ""
lang_c_crypto="libgcrypt-devel gpgme-devel openssl-devel gnutls-devel mbedtls-devel"
# ""
lang_c_dbase="sqlite-devel postgresql mysql mariadb hiredis-devel mongo-c-driver-devel"
# ""
lang_c_network="curl"
# ""
pkgs_lang_c="dbus xauth xterm cmake base-devel clang llvm lldb gdb pkgconf splint check-devel log4c-devel pcre-devel json-c-devel json-glib-devel yajl-devel libyaml-devel lcov swig gcc-fortran"
# ddd valgrind doxygen premake4 cppcheck bcunit-devel
## pip install [--break-system-packages] --user xx: meson ninja scons

pkgs_lang_java="dbus xauth xterm openjdk11 openjdk apache-ant"
# apache-maven gradle sbt
#default_path_to_fx="[/usr/lib/jvm|/opt]/javafx-sdk-[11]/lib"
# dnld: https://download2.gluonhq.com/openjfx/[11]/openjfx-[11]_[linux]-[x64]_bin-[sdk|jmods].zip


pkgs_lang_scm="Gauche guile"

pkgs_lang_hs="ghc ncurses-libtinfo-devel stack"

pkgs_lang_scala="dbus xauth xterm openjdk11 openjdk apache-ant"
# scala
pkgs_lang_ml="ocaml opam dune"

pkgs_lang_lisp="sbcl clisp"


pkgs_lang_go="go gopm"

pkgs_lang_cs="dbus xauth xterm mono msbuild fsharp"
## NOTE: missing *.dll(s) errors - edit [/usr/local]/etc/mono/config
##  example: libgobject-2.0 -> libgobject-2.0-0.dll
# dnld: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
# gtk-sharp

pkgs_lang_clj=""
# clojure leiningen
pkgs_lang_fs="dbus xauth xterm mono msbuild fsharp"

pkgs_lang_rs="cargo rust"

pkgs_lang_rb="ruby"

pkgs_lang_swift="libbsd-devel libedit-devel icu-devel ncurses-libs"
# dnld: https://download.swift.org/swift-[5.6]-release/[amazonlinux2][-aarch64]/swift-[5.6]-RELEASE/swift-[5.6]-RELEASE-[amazonlinux2][-aarch64].tar.gz[.sig]
